
CANONICAL_METADATA = {
    'desconhecido': {'code': 0, 'description': 'unknown'},
    'Implant': {'code': 1, 'description': 'implant'},
    'Inhal': {'code': 2, 'description': 'inhalation'},
    'Instill': {'code': 3, 'description': 'instillation'},
    'N': {'code': 4, 'description': 'nasal'},
    'O': {'code': 5, 'description': 'oral'},
    'P': {'code': 6, 'description': 'parenteral'},
    'R': {'code': 7, 'description': 'rectal'},
    'SL': {'code': 8, 'description': 'sublingual/buccal/oromucosal'},
    'TD': {'code': 9, 'description': 'transdermal'},
    'V': {'code': 10, 'description': 'vaginal'},
}

CANONICAL_CODE_MAP = {k: v["code"] for k, v in CANONICAL_METADATA.items()}
CANONICAL_DESCRIPTIONS = {k: v["description"] for k, v in CANONICAL_METADATA.items()}

BASE_CANONICAL_KEYWORDS = {
    'Implant': [
        'Braço não especificado',
        'IN',
        'Intra Uterina',
        'Intra-uterina',
        'Intra-uterine',
        'Intrauterina', 
        'Subdermica',
        'Subdérmica',
        'Subdérmico',
        'Via Subdérmica',
        'Via subdérmica',
        'Via subdérrmica',
        'intra uterino',
        'intrauterina',
    ],
    'Inhal': [
        'AEROSOL',
        'AEROSSOL',
        'CA',
        'EB',
        'ES',
        'EV / INALATORIO',
        'IA',
        'INAL',
        'INALANTE',
        'INALATORIA',
        'INALATORIO',
        'INALATÓRIA',
        'INALATÓRIO',
        'INALATÓRIO ORAL',
        'INALAÇÃO',
        'Inalado',
        'Inalador',
        'Inalatoria',
        'Inalatoria.',
        'Inalatorio',
        'Inalatória',
        'Inalatória Oral',
        'Inalatória nasal',
        'Inalatória oral',
        'Inalatória, E2B R2 Code: 050 - Other',
        'Inalatório',
        'Inalatório (oral)',
        'Inalatório Oral',
        'Inalatório Via Nasal',
        'Inalatório Via Oral',
        'Inalaçao',
        'Inalação',
        'Inalação Oral',
        'Inalação respiratória',
        'Inalaório',
        'Inhalation',
        'Inhalation use',
        'NEBULIZAÇÃO',
        'Oral inhalation',
        'Pó para inalação',
        'RESPIRATÓRIA',
        'Respiratory (inhalation)',
        'Respiratory (inhalation) Formulation: Aerosol',
        'Respiratory (inhalation) Formulation: Inhalant Powder',
        'Respiração inalatória',
        'TO',
        'USO INALATÓRIO (ORAL)',
        'USO INALATÓRIO POR VIA ORAL',
        'USO ORAL (INALATÓRIO)',
        'Uso Inalatório',
        'Uso Inalatório Oral',
        'Uso Inalatório por Via Oral',
        'Uso Inalatório por via Oral',
        'Uso inalatório',
        'Uso inalatório Oral',
        'VIA ALVEOLAR',
        'VIA INALATÓRIA',
        'Via Inalatória',
        'Via Inalatória Oral',
        'Via inalatoria',
        'Via inalatória',
        'Via inalatória (oral)',
        'Via inalatória oral',
        'Vick inalado no nariz',
        'inalada',
        'inalador',
        'inalalacao',
        'inalatoria',
        'inalatorio',
        'inalatorio oral',
        'inalatória',
        'inalatória oral',
        'inalatório',
        'inalatório (oral)',
        'inalatório oral',
        'inalação',
        'oral (inalatório)',
        'oral (uso inalatório)',
        'oral inhalation',
        'pulmonar',
        'repiratória (inalação)',
        'respiratory (inhalation)',
        'respiratória',
        'respiratória (inalação)',
        'uso inalatório (oral)',
        'uso oral (inalatório)',
        'via inalatória',
        'via inalatória oral',
        'via inalatório',
    ],
    'Instill': [
        'Auricular (otic)',
        'BIC',
        'Colírio',
        'Em ambos os olhos',
        'Instilação pulmonar endotraqueal',
        'OCULAR',
        'OFTALMICA',
        'OFTÁLMICA',
        'OTOLÓGICO',
        'Ocular',
        'Ocular use',
        'Ofitálmica',
        'Oftalmica',
        'Oftalmico',
        'Oftálmica',
        'Oftálmico',
        'Ophthalmic',
        'Otológica',
        'Otológico',
        'Solução oftálmica',
        'TOPICO OCULAR',
        'Tópica ocular',
        'Tópico Oftálmico',
        'Uso auricular',
        'Uso ocular',
        'Uso oftálmico',
        'VIA OCULAR',
        'VIA OFTÁLMICA',
        'VIA OTOLÓGICA',
        'Via Ocular',
        'Via endotraqueobrônquica',
        'Via ocular',
        'Via oftálmica',
        'auricular',
        'in right eye',
        'irrigação vesical',
        'ocular',
        'oftalmologica',
        'oftalmológica',
        'oftamológica',
        'oftálmica',
        'otológica, E2B R2 Code: 065 - Unknown',
        'solução otologica',
        'uretral',
        'uso ocular',
        'uso oftálmico',
        'via ocular',
        'via oculares',
        'via oftalmica',
        'via oftálmica',
        '´Tópico - ocular',
    ],
    'N': [
        'INTRANASAL',
        'Intra-nasal',
        'Intranasal',
        'NASAL',
        'Nasal',
        'Nasal use',
        'SA',
        'USO INTRANASAL',
        'VIA NASAL',
        'Via Nasal',
        'Via nasal',
        'Via nasal / solução spray nasal',
        'intra nasal',
        'intranasal',
        'nasal',
        'oral/nasal',
        'spray nasal',
        'usado no nariz',
        'via nasal',
    ],
    'O': [
        '.V.O',
        '0ral',
        '1 cápsula via oral de manhã e 1 cápsula via vaginal de noite',
        '100mg 2 cps (1 cp manhã e 1 cp a noite)',
        '2 cápsulas via oral e 2 cápsulas via vaginal',
        'Administrada pela gastrostomia',
        'Administrado por via oral',
        'Administração por via oral.',
        'Administração via oral.',
        'COMPRIMIDO',
        'CP',
        'Cateter Nasoenteral',
        'Comprimido',
        'Dor',
        'ENTERAL',
        'EVI',
        'Enteral',
        'Exposição pelo leite materno',
        'GASTRO',
        'GASTROENTÉRICA',
        'GASTROMIA',
        'GASTROSTOMIA',
        'GTM',
        'GTT',
        'Gastric use',
        'Gastroenteral',
        'Gastrostomia',
        'Gastrotomia',
        'GÁSTRICA',
        'Inalação oral',
        'Intravascular. oral e intracavitario',
        'JEJUNOSTOMIA',
        'Jejunostomia',
        'MSE',
        'NASOENTERAL',
        'NASOGASTRICA',
        'Nasoenteral',
        'Nasoenteric tube',
        'Nasogastric tube',
        'Nasogastric tube, E2B R2 Code: 050 - Other',
        'Nasogástrica',
        'ORAL',
        'ORAL (VO)',
        'ORAL E EV',
        'ORAL,',
        'ORLA',
        'OROENTERAL',
        'Oal',
        'Oral',
        'Oral / Transplacentária',
        'Oral Formulation: Capsule',
        'Oral Formulation: Film-coated tablet',
        'Oral Formulation: Tablet',
        'Oral Formulation: Unknown / Oral Formulation: Unknown',
        'Oral use',
        'Oral | Sonda Nasogastrica',
        'Oral.',
        'PARENTERAL',
        'Parenteral',
        'Produto de uso oral (porem não informado)',
        'Relator informou que foi administrado via oral',
        'S.N.E. (SONDA NASOENTERICA)',
        'SNE',
        'SNE / Gastro',
        'SNG',
        'SOG',
        'SONDA',
        'SONDA (SNE)',
        'SONDA ENTERAL',
        'SONDA NASO',
        'SONDA NASOENTERAL',
        'SONDA NASOENTÉRICA',
        'SONDA NASOENTÉRICO',
        'SONDA NASOGASTRICA',
        'SONDA NASOGÁSTRICA',
        'SONDA NASOGÁTRICA',
        'SONDA ORO',
        'SONDA OROGÁSTRICA',
        'SONDA OROGÁTRICA',
        'Sona nasoenteral',
        'Sonda',
        'Sonda (não especificada), E2B R2 Code: 050 - Other',
        'Sonda Enteral',
        'Sonda GTT',
        'Sonda Nasoenteral',
        'Sonda Nasoenteral.',
        'Sonda Nasoenterica',
        'Sonda Nasoentérica',
        'Sonda Nasogástrica',
        'Sonda Oro/nasoenterica',
        'Sonda de Gastrostomia',
        'Sonda enteral',
        'Sonda enteral (GTT)',
        'Sonda entérica',
        'Sonda gástrica',
        'Sonda naso enteral',
        'Sonda nasoenteral',
        'Sonda nasoenterica',
        'Sonda nasoentérica',
        'Sonda nasogastrica',
        'Sonda nasogástrica',
        'Sonda orogástrica',
        'Sonda oronasoenteral',
        'Subretinal use',
        'Tubo nasogástrico',
        'Tópico e Via Oral',
        'USO ORAL',
        'USO ORAL OU VIA TUBO DE GASTROSTOMIA',
        'Uso Oral',
        'Uso oral',
        'V.0',
        'V.O',
        'V.O.',
        'VI',
        'VIA',
        'VIA ENTERAL',
        'VIA GASTROENTÉRICA',
        'VIA GTT',
        'VIA NASOENTERAL',
        'VIA NASOENTÉRICA',
        'VIA ORAL',
        'VIA SONDA ENTERAL',
        'VIA SONDA NASOENTERAL',
        'VIA SONDA NASOENTÉRICA',
        'VIA SONDA OROGASTRICA',
        'VIA SONDAENTERAL',
        'VIO ORAL',
        'VO',
        'VO,',
        'VSNE',
        'Vaginal e oral',
        'Via Gastroentérica',
        'Via ORAL',
        'Via Oral',
        'Via Oral.',
        'Via Sonda',
        'Via Sonda Nasoenteral',
        'Via gastroentérica',
        'Via gastrostomia',
        'Via gástrica',
        'Via leite materno',
        'Via leite materno, E2B R2 Code: 050 - Other',
        'Via nasoenteral',
        'Via nasoentérica',
        'Via oral',
        'Via oral com água.',
        'Via oral, E2B R2 Code: 050 - Other',
        'Via oral.',
        'Via sonda Nasoenteral',
        'Via sonda enteral',
        'Via sonda nasoenteral',
        'Via sonda nasoentérica',
        'Via sonda nasogastrica',
        'Via sonda nasogástrica',
        'Via sonda.',
        'Via sondanasoenteral',
        'Via tubo naso entérico',
        'Vira oral',
        'Vita Oral',
        'Vo',
        'Xarope',
        '_x0009_ VO',
        'administrado via sonda gástrica',
        'comprimido revestido',
        'cp',
        'cápsula',
        'enteral',
        'enteral, E2B R2 Code: 065 - Unknown',
        'evi',
        'gastrica',
        'gastro',
        'gastroenteral, E2B R2 Code: 050 - Other',
        'gastrostomia',
        'gastrotosmia',
        'gtt',
        'inalação por via oral',
        'injetável e oral',
        'jejunal',
        'jejunostomia',
        'mse',
        'nasoenteral',
        'nasoentérica',
        'nasogástrica',
        'nasogástrico',
        'oRAL',
        'orAL',
        'oral',
        'orla',
        'parenteral',
        'sne',
        'sonda',
        'sonda enteral',
        'sonda enteral (GTT)',
        'sonda enterica',
        'sonda entérica',
        'sonda gastrica',
        'sonda gástrica',
        'sonda gátrica',
        'sonda naso enteral',
        'sonda naso/esofágica',
        'sonda nasoeneral',
        'sonda nasoenteral',
        'sonda nasoenteral, E2B R2 Code: 050 - Other',
        'sonda nasoenterica',
        'sonda nasoentérica',
        'sonda nasogastrica',
        'sonda nasogastrica enteral',
        'sonda nasogástrica',
        'sonda nasogástrica enteral',
        'sonda ora/nasoenterica',
        'sonda oroenteral',
        'sonda orogastrica',
        'sonda orográstrica',
        'sonda orogástrica',
        'sonda orogátrica',
        'sondanasoenteral',
        'sondanasoentérica',
        'sondanasogástrica',
        'v.o',
        'vi oral',
        'via Oral',
        'via enteral',
        'via gastrostomia',
        'via gastrostomia conforme descrito no relato',
        'via jejunal',
        'via nasoenteral',
        'via ora',
        'via oral',
        'via oral em cada canto da boca',
        'via oral ou via tudo de gastrostomia',
        'via oral.',
        'via oreal',
        'via orla',
        'via sonda',
        'via sonda nasoenteral',
        'via sonda nasoenterica',
        'via sonda nasoentérica',
        'via sonda nasogástrica',
        'via sondanasoenteral',
        'via tubo nasogástrico, E2B R2 Code: 050 - Other',
        'viaoral',
        'vio oral',
        'vira oral',
        'vo',
        'Óral',
    ],
    'P': [
        '"Injeção"',
        '"aplicado no bumbum"',
        '(INTRAVENOUS DRIP)',
        '- Endovenosa',
        '1 comprimido por dia',
        '1) Intravenous (not otherwise specified) 2) Oral',
        'ACESSO VENOSO PERIFERICO',
        'AMP',
        'AMPOLA',
        'ANDOVENOSA',
        'ANESTESIA LOCORREGIONAL',
        'AVP (Acesso venoso periférico)',
        'Acesso periférico em membro superior direito',
        'Adesivo transdérmico',
        'Adesivos Transdérmicos',
        'Administrado via EVI (infusão lenta).',
        'Administrado via intravenosa',
        'Administrar 2 ml (Agora via Intramuscular).',
        'Administrado oral e intravenoso',
        'Administrado oral e intravenosa',
        'Oral e intravenoso',
        'Oral e intravenosa',
        'Oral intravenoso',
        'Oral intravenosa',
        'Oral venoso',
        'Oral venosa',
        'Oral endovenoso',
        'Oral endovenosa',
        'Oral parenteral',
        'Oral intramuscular',
        'Oral intramus',
        'Oral subcutaneo',
        'Oral subcutanea',
        'Oral hipodermoclise',
        'Via oral e intravenosa',
        'Via oral e intravenoso',
        'Via oral intramuscular',
        'Via oral subcutanea',
        'Via oral subcutâneo',
        'Via oral intramuscular e intravenosa',
        'Via oral e parenteral',
        'Ampola',
        'Anestesia regional',
        'Aplicação em membro superior esquerdo',
        'Arterial',
        'arterial',
        'BC',
        'BIC - IV',
        'BIC/INTRAVENOSA',
        'BOLSA',
        'BOMBA DE INFUSÃO CONTÍNUA',
        'BOMBA PCA',
        'Bloqueio de PICC',
        'Bolus',
        'Bolus (I.V.)',
        'Bolus Intravenoso',
        'Bolus endovenoso',
        'Bolus intravenoso',
        'Bom de infusão contínua',
        'Bomba de Infusão',
        'Bomba de Infusão contínua',
        'Bomba de infusão',
        'Bomba de infusão continua',
        'Bomba de infusão contínua',
        'Bomba de infusão contínua.',
        'Bomba subcutânea',
        'Bortezomibe: Subcutânea // Lenalidomida: Oral',
        'CATETER  PERIDURAL',
        'CULTANEA',
        'CUTANEA',
        'CUTÂNEA',
        'CVC-TI – cateter venoso central totalmente implantado',
        'Cateter  peridural',
        'Cateter totalmente implantado em Subclávia Direita',
        'Catéter Epidural',
        'Catéter venoso central',
        'Central',
        'Circuito de Infusão',
        'Comprimido Revestido',
        'Deltoide esquerdo',
        'Deltóide Direito',
        'Deltóide Esquerdo',
        'E v',
        'E.V',
        'E.V.',
        'E.V..',
        'E2B R2 Code: 050 - Other',
        'E2B R2 Code: 051 - Parenteral',
        'EM',
        'ENCOVENOSA',
        'END',
        'ENDEVENOSA',
        'ENDEVONOSO',
        'ENDO VENOSA',
        'ENDOBENOSA',
        'ENDOENOSA',
        'ENDOENOSO',
        'ENDOSCOPIA',
        'ENDOVCENOSA',
        'ENDOVENODO',
        'ENDOVENOMA',
        'ENDOVENOS',
        'ENDOVENOSA',
        'ENDOVENOSA / INTRAMUSCULAR',
        'ENDOVENOSA DIRETO',
        'ENDOVENOSA POR BIC',
        'ENDOVENOSA, INTRAMUSCULAR, SUBCUTÂNEA',
        'ENDOVENOSA.',
        'ENDOVENOSO',
        'ENDOVENOSO/INTRAMUSCULAR',
        'ENDOVENOSOS',
        'ENDOVENSA',
        'ENDOVENSO',
        'ENDOVENSOSA',
        'ENDOVENÓSA',
        'ENDOVEONSA',
        'ENDOVEOSO',
        'ENDOVERNOSA',
        'ENDOVESONA',
        'ENDOVESONO',
        'ENDOVEVNOSA',
        'ENDOVONOSO',
        'ENDOVRNOSA',
        'ENDVENOSA',
        'ENOVENOSO',
        'ENSOVENOSA',
        'ENTRATECAL',
        'ENVOVENOSA',
        'ENdovenosa',
        'EPIDURAL',
        'EV',
        'EV (BOLUS)',
        'EV - BI',
        'EV - BIC',
        'EV / IV',
        'EV BI',
        'EV BOLUS',
        'EV Bolus',
        'EV bolus',
        'EV central',
        'EV e posteriormente VO',
        'EV em "bolus"',
        'EV,',
        'EV, IM  ou SC',
        'EV,,',
        'EV-',
        'EVB',
        'EVC',
        'Eendovenosa',
        'Emdovenosa',
        'Endenosa',
        'Endevenosa',
        'Endevenoso',
        'Endevonosa',
        'Endivenosa',
        'Endo',
        'Endo Venosa',
        'Endo Venoso',
        'Endo venoso',
        'Endoenoso',
        'Endoivenosa',
        'Endonenosa',
        'Endosvenosa',
        'Endovanosa',
        'Endovedosa',
        'Endovenoda',
        'Endovenosa',
        'Endovenosa (Acesso periférico)',
        'Endovenosa direta',
        'Endovenosa direta.',
        'Endovenosa e Intramuscular',
        'Endovenosa e oral',
        'Endovenosa em bomba de infusão',
        'Endovenosa periférica',
        'Endovenosa-direta',
        'Endovenosa.',
        'Endovenosa/subcutânea',
        'Endovenose',
        'Endovenoso',
        'Endovenoso (EV)',
        'Endovenoso.',
        'Endovenossa',
        'Endovensa',
        'Endovenso',
        'Endovensoa',
        'Endoveonoso',
        'Endoveoso',
        'Endovesona',
        'Endovesono',
        'Endovesosa',
        'Endovnosa',
        'Endvenosa',
        'Endvenoso',
        'Enovenoso',
        'Epidural',
        'Epidural use',
        'Espinhal',
        'Ev',
        'Extracorpórea',
        'FEMORAL',
        'FRASCO AMPOLA',
        'Frasco',
        'Fístula de hemodiálise (sistema)',
        'GOTEJAMENTO INTRAVENOSO',
        'Gastroenteral, E2B R2 Code: 050 - Other',
        'Genuxal 1.200mg diluído em 500ml de soro fisiológico 0,9%,',
        'Gotejamento IV',
        'Gotejamento intravenoso',
        'HEMODIÁLISE',
        'HIPODERMOCLISE',
        'HIPODERMÓCLISE',
        'Hemodiálise',
        'Hipodermoclise',
        'Hipodermóclise',
        'I M',
        'I.M',
        'I.Muscular',
        'I.V',
        'I.V.',
        'I.V. boulos',
        'IBVIC',
        'IM',
        'IM / EV',
        'IM OU EV',
        'IM- IV',
        'IM/ IV',
        'IM/EV',
        'IM/IV',
        'IM/IV/Retal',
        'IM/SC',
        'INFUSAO',
        'INFUSAO INTRAVENOSA',
        'INFUSÃO',
        'INFUSÃO INTRAVENOSA',
        'INJETAVEL',
        'INJETAVEL ENDOVENOSO',
        'INJETAVÉL',
        'INJETÁVEL',
        'INJEÇÃO',
        'INJEÇÃO NÃO ESPECIFICADA',
        'INJEÇÃO NÃO ESPECIFICADA, E2B R2 Code: 065 - Unknown',
        'INRAVENOSA',
        'INSTRAMUSCULAR',
        'INTARVENOSA',
        'INTAVENOSA',
        'INTERTECAL',
        'INTERTERCAL',
        'INTEVENOSA',
        'INTRA MUSCULAR',
        'INTRA TECAL',
        'INTRA VENOSA',
        'INTRA-ARTERIAL',
        'INTRA-VENOSO',
        'INTRACARDÍACA',
        'INTRADÉRMICA',
        'INTRALESIONAL',
        'INTRAMUSCILAR',
        'INTRAMUSCULAR',
        'INTRAMUSCULAR DELTOIDE D',
        'INTRAOCULAR',
        'INTRARAQUIDIANA',
        'INTRATECA.',
        'INTRATECAL',
        'INTRATERCAL',
        'INTRAVASCULAR',
        'INTRAVE',
        'INTRAVENOA',
        'INTRAVENOS',
        'INTRAVENOSA',
        'INTRAVENOSA (SEM MAIORES ESPECIFICAÇÕES)',
        'INTRAVENOSA DE OUTRA FORMA NÃO ESPECIFICADA',
        'INTRAVENOSA DIRETA',
        'INTRAVENOSA.',
        'INTRAVENOSO',
        'INTRAVENOSSA',
        'INTRAVENOSa',
        'INTRAVENOUS OTHERWISE NOT SPECIFIED',
        'INTRAVENSA',
        'INTRAVEOSA',
        'INTRAVESICAL',
        'INTRAVITREA',
        'INTRAVNOSA',
        'INTRETECAL',
        'INTRETEGAL',
        'INTREVENOSA',
        'INTREVESICAL',
        'INTROVENOSA',
        'INTRTAVENOSA',
        'IP',
        'ITRAMUSCULAR',
        'IV',
        'IV BIC',
        'IV DIRETO',
        'IV Direta',
        'IV Direto',
        'IV EM BOLUS',
        'IV INFUSAO',
        'IV INFUSÃO',
        'IV INfusão',
        'IV Infusão',
        'IV contínuo',
        'IV direto',
        'IV em BIC',
        'IV em Bomba de Infusão',
        'IV infusão',
        'IV infusão contínua',
        'IV- IM',
        'IV- bomba de infusão',
        'IV.',
        'IV/ IM',
        'IV/SC',
        'IVAD',
        'IVBC',
        'IVBIC',
        'IVD',
        'IVO',
        'Inetável',
        'Inf Intravenosa',
        'Inf intravenosa',
        'Infiltração em articulações mandibulares',
        'Infiltração local',
        'Informou somente que é injetável',
        'Infusão',
        'Infusão Contínua',
        'Infusão IV',
        'Infusão Intravenosa',
        'Infusão contínua',
        'Infusão em BIC (Bomba de Infusão Contínua).',
        'Infusão endovenosa',
        'Infusão intravenosa',
        'Infusão intravenosa em bolus',
        'Inicialmente via intramuscular',
        'Injection not otherwise specified',
        'Injetavel',
        'Injetavel Subcutêneo Ou Intravenoso',
        'Injetável',
        'Injetável - Via Intravenosa',
        'Injetável EV',
        'Injetável via veia periférica, E2B R2 Code: 050 - Other',
        'Injetável, E2B R2 Code: 050 - Other',
        'Injetável, E2B R2 Code: 051 - Parenteral',
        'Injetável.',
        'Injetávél',
        'Injeção',
        'Injeção não especificada',
        'Injeção não especificada, E2B R2 Code: 065 - Unknown',
        'Injeção, E2B R2 Code: 050 - Other',
        'Inravenosa',
        'Intavenosa',
        'Intavenoso',
        'Interavenosa',
        'Intra Muscular',
        'Intra Venoso',
        'Intra arterial',
        'Intra articular',
        'Intra muscular',
        'Intra venosa',
        'Intra vitrea',
        'Intra-arterial',
        'Intra-muscular',
        'Intra-venosa',
        'Intra-venoso',
        'Intraarterial',
        'Intracardíaca',
        'Intracavernosa',
        'Intracavernous use',
        'Intracavitária',
        'Intracoronariana',
        'Intradermal',
        'Intradermica',
        'Intradérmica',
        'Intraenosa',
        'Intramuscular',
        'Intramuscular (IM)',
        'Intramuscular Formulation: Injection',
        'Intramuscular e Endovenosa',
        'Intramuscular e Intradérmica',
        'Intramuscular e intradérmica',
        'Intramuscular na coxa direita',
        'Intramuscular no braço direito',
        'Intramuscular use',
        'Intramuscular, braço direito',
        'Intramuscular- deltoide direito',
        'Intramuscular- deltoide esquerdo',
        'Intraocular use',
        'Intrapericardial',
        'Intrarraquidina',
        'Intratecal',
        'Intratecal (raquidiana)',
        'Intrathecal',
        'Intrathecal use',
        'Intravascular',
        'Intravenosa',
        'Intravenosa (IV)',
        'Intravenosa (Não especioficada)',
        'Intravenosa (não especificada)',
        'Intravenosa (não especificado de outra forma)',
        'Intravenosa (sem maiores especificações)',
        'Intravenosa Central',
        'Intravenosa bolus',
        'Intravenosa e subcutânea (granulokine).',
        'Intravenosa em bolus',
        'Intravenosa ou subcutânea',
        'Intravenosa, E2B R2 Code: 065 - Unknown',
        'Intravenosa.',
        'Intravenosaq',
        'Intravenoso',
        'Intravenoso (não especificado de outra forma)',
        'Intravenoso bolus',
        'Intravenoso em bolus',
        'Intravenoso por Circulação Extracorporea',
        'Intravenoso por gotejamento',
        'Intravenoso.',
        'Intravenosp',
        'Intravenossa',
        'Intravenous',
        'Intravenous (not otherwise specified)',
        'Intravenous bolus',
        'Intravenous drip',
        'Intravenous use',
        'Intravenovo',
        'Intravenposa',
        'Intravenpsa',
        'Intravensa',
        'Intravesical',
        'Intravitrea',
        'Intravitreal',
        'Intravitreal use',
        'Intravitreal, E2B R2 Code: 050 - Other',
        'Intravneosa',
        'Intravítrea',
        'Intravítreo',
        'Intrevenosa',
        'Intrevwnosa',
        'Intrravenosa',
        'Intrvenosa',
        'Intrvenoso',
        'Intrvenossa',
        'Inytravenoso',
        'Itravenosa',
        'Itravenoso',
        'Iv',
        'Iv direto',
        'KINTRAVENOSA',
        'LOCAL - CATETER',
        'MSD - Subcutânea',
        'Músculo vasto lateral esquerdo',
        'NF',
        'Nos pulsos',
        'Outra via de administração (Infusão)',
        'PERIDURAL',
        'PERITONEAL',
        'PRODUTO DE USO INTRAMUSCULAR (VIA DE ADM. NÃO INFORMADA)',
        'PUNÇÃO LOMBAR NA COLUNA VERTEBRAL',
        'Parenteral, E2B R2 Code: 051 - Parenteral',
        'Peridual',
        'Peridural',
        'Periférico',
        'Periférica',
        'Por via intramuscular no vasto lateral direito',
        'Por via intramuscular no vasto lateral esquerdo',
        'Prime',
        'Punção lombar',
        'PÓ LIOFILIZADO',
        'Pó',
        'Pó para solução injetável',
        'Quimioterapico',
        'RAQUEANESTESIA',
        'RAQUI',
        'RAQUIANESTESIA',
        'RAQUIANESTESIA - INTRATECAL',
        'RAQUIDIANA',
        'RAQUIMEDULAR',
        'Raqui anestesia',
        'Raquidiana',
        'Raquidural',
        'S.C',
        'S.C profundo',
        'S.C.',
        'SC',
        'SC - Subcutânea',
        'SC E EV',
        'SC PROFUNDO',
        'SOL INJETAVEL',
        'SOLUÇÃO INJETÁVEL',
        'SOLUÇÃO INTRAVENOSA',
        'SUB',
        'SUB CUTANEA',
        'SUB CUTÂNEA',
        'SUBARACNOIDE',
        'SUBARACNÓIDEO',
        'SUBCLAVIA DIREITA',
        'SUBCTANIA',
        'SUBCULTÂNEA',
        'SUBCUTANEA',
        'SUBCUTANEO',
        'SUBCUTANIA',
        'SUBCUTÂENO',
        'SUBCUTÂNEA',
        'SUBCUTÂNEA.',
        'SUBCUTÂNEO',
        'SUBCUTÂNEOP',
        'SUBCUTÂNIA',
        'SUBCUTÃNEA',
        'Sol inj',
        'Solução injetavel',
        'Solução injetável',
        'Solução intravenosa',
        'Sonda Nasoduodenal',
        'Sub Cutânea',
        'Sub cutÂnea',
        'Sub cutânea',
        'Sub cutâneo',
        'Subaracnoidea',
        'Subaracnóidea',
        'Subctânea',
        'Subcutan.-Bomba',
        'Subcutanea',
        'Subcutaneo',
        'Subcutaneous',
        'Subcutaneous Formulation:  Unknown',
        'Subcutaneous Formulation: Unknown',
        'Subcutaneous use',
        'SubcutaneousSubcutaneousSubcutaneousSubcutaneousSubcutaneous',
        'Subcutanêa',
        'SubcutÂneo',
        'Subcutânea',
        'Subcutânea (SC)',
        'Subcutânea - braço direito',
        'Subcutânea profunda',
        'Subcutânea-Bomba',
        'Subcutânea.',
        'Subcutâneo',
        'Subcutâneo Ou Intravenoso',
        'Subcutâneo uso',
        'Subcutâneo-Bomba',
        'Subcutânia',
        'Sucutânea',
        'Suncutânea',
        'Transmamaria',
        'Transmammary',
        'Transmamário',
        'Transplacental',
        'Transplacentária',
        'Transplacentário',
        'USO INTRAVENOSO',
        'Ultima aplicação 21-Set-2023',
        'Uso Intravenoso',
        'Uso Parenteral/ Anestesia Locorregional',
        'Uso Subcutâneo',
        'Uso intraocular',
        'Uso intravenoso',
        'Uso subcutânea',
        'Uso subcutâneo',
        'VE',
        'VENOSA',
        'VENOSA/EPIDURAL',
        'VENOSO',
        'VIA  INTRAVENOSA',
        'VIA ENDOENOSA',
        'VIA ENDOVENOSA',
        'VIA ENDOVENOSO',
        'VIA HIPODERMÓCLISE',
        'VIA IM',
        'VIA INJETAVEL',
        'VIA INTRACAVERNOSA',
        'VIA INTRAMUSCULAR',
        'VIA INTRATECAL',
        'VIA INTRAVENOSA',
        'VIA INTRAVENOSA E ORAL',
        'VIA INTRAVENOSAS',
        'VIA INTRAVENOSO',
        'VIA INTRAVESICAL',
        'VIA INTRECAL',
        'VIA SONDA',
        'VIA SUBARACNOIDE',
        'VIA SUBCTÂNEA',
        'VIA SUBCTÃNEA',
        'VIA SUBCUTANEA',
        'VIA SUBCUTÂNEA',
        'VIA SUBCUTÃNEA',
        'VIa intravenosa',
        'Vacinada no braço direito, E2B R2 Code: 065 - Unknown',
        'Vasto Lateral D',
        'Venosa',
        'Venoso',
        'Via E.V',
        'Via Endovenosa',
        'Via Endovenoso',
        'Via Endovesona',
        'Via Epidural',
        'Via Intradermica',
        'Via Intramuscular',
        'Via Intratecal',
        'Via Intravascular',
        'Via Intravenosa',
        'Via Intravenosa.',
        'Via Intravenoso',
        'Via Intravesical',
        'Via Raquidiana',
        'Via Subcutânea',
        'Via de administração reportada como injeção',
        'Via endotraqueal',
        'Via endovenosa',
        'Via endovenosa.',
        'Via epidural',
        'Via epidural (raquidiana)',
        'Via extracorpórea',
        'Via infusão',
        'Via intra venosa',
        'Via intra-arterial',
        'Via intramuscular',
        'Via intramuscular (IM) na região glútea',
        'Via intramuscular.',
        'Via intratecal',
        'Via intratecal.',
        'Via intravenosA',
        'Via intravenosa',
        'Via intravenosa (IV)',
        'Via intravenosa direta',
        'Via intravenosa e via oral',
        'Via intravenosa lento',
        'Via intravenosa,',
        'Via intravenosa.',
        'Via intravenossa',
        'Via intravesical',
        'Via parenteral (não especificada)',
        'Via peridural',
        'Via sonda',
        'Via sonda naso duodenal',
        'Via subaracnoídea',
        'Via subcutânea',
        'Via subcuânea',
        'Via subradnoidea',
        'Via venosa.',
        '_x0009_ EV',
        '_x007f_intravenosa',
        'acesso central lado direito',
        'acesso venoso',
        'administrada no musculo deltoide direito',
        'ampola',
        'anestesia Raqui',
        'aplicação no vasto lateral',
        'bolus',
        'bolus endovenoso',
        'bolus intravenoso',
        'bomba de infusão',
        'boulos intravenosa',
        'comprimido',
        'comprimidos',
        'corpo intracavernoso',
        'cutanea',
        'cutâneo',
        'dose de 120 mg, por via subcutânea',
        'e.v',
        'e.v.',
        'edovenoso',
        'em bolus EV',
        'em bolus endovenso',
        'endeovenosa',
        'endeovenoso',
        'endevenosa',
        'endevenoso',
        'endeveoso',
        'endevonosa',
        'endo',
        'endo venosa',
        'endobenosa',
        'endodenoso',
        'endoenoso',
        'endonenosa',
        'endonvenosa',
        'endoovenosa',
        'endoovenoso',
        'endotraqueal',
        'endovanosa',
        'endoveno',
        'endovenoa',
        'endovenodso',
        'endovenonsa',
        'endovenooso',
        'endovenos',
        'endovenos0',
        'endovenosa',
        'endovenosa (IV INFUSÃO)',
        'endovenosa em bomba de infusão',
        'endovenosa intermitente',
        'endovenosa ou intramuscular',
        'endovenosa, seguida de via enteral',
        'endovenoso',
        'endovenoso .',
        'endovenoso.',
        'endovenoso/ epidural',
        'endovenosos',
        'endovenossa',
        'endovensa',
        'endovenso',
        'endovensoo',
        'endovensos',
        'endovensosa',
        'endovensoso',
        'endoveosa',
        'endoveso',
        'endovesona',
        'endovesonso',
        'endvenosa',
        'endvenoso',
        'enedovenosa',
        'enfdovenoso',
        'enfovenosa',
        'enodevenosa',
        'enodvenosa',
        'enodvenoso',
        'enovenosa',
        'enovenoso',
        'envodenoso',
        'envovenosa',
        'epidural',
        'esndovenoso',
        'espinhal',
        'espinhal - intratecal',
        'ev',
        'frasco ampola',
        'gotejamento IV',
        'gotejamento intravenoso',
        'hemodiálise',
        'hipodermóclise',
        'i.v',
        'iNTRAVENOSA',
        'iV',
        'im',
        'im e intralesional',
        'im/ev',
        'imtravenoso',
        'indovenosa',
        'inejtável',
        'inf intravenosa',
        'infetável',
        'infiltration',
        'infiltração',
        'infusaõ venosa',
        'infusão',
        'infusão EV',
        'infusão Intravenosa',
        'infusão contínua',
        'infusão de propofol para sedação',
        'infusão endovenosa',
        'infusão intravenosa',
        'infusão intravenosa em 10 minutos',
        'infusão intrevenosa',
        'infusão port-a-cath, E2B R2 Code: 050 - Other',
        'injação não especificada',
        'injetavel',
        'injetavel intramuscular',
        'injetável',
        'injeção',
        'injeção em caneta preenchida',
        'injeção no braço direito',
        'injeção não especificada',
        'injeção não especificada, E2B R2 Code: 050 - Other',
        'injeção não especificada, E2B R2 Code: 065 - Unknown',
        'injeção não especificado, E2B R2 Code: 065 - Unknown',
        'injeção subcutânea',
        'inrtamuscular',
        'inrtavenosa',
        'instravenoso',
        'intarvenosa',
        'intavenosa',
        'intavenoso',
        'intra dermica',
        'intra muscular',
        'intra venosa',
        'intra venoso',
        'intra- vitrea',
        'intra-amniótica',
        'intra-arterial',
        'intra-articular',
        'intra-muscular',
        'intra-uterine',
        'intra-venosa',
        'intracavernosa',
        'intracerebral',
        'intracerebroventricular',
        'intracervical',
        'intracoronariana',
        'intracoronária',
        'intracórnea',
        'intradermica',
        'intradiscal',
        'intraenoso',
        'intrahepática',
        'intralesional',
        'intralinfática',
        'intramedular',
        'intrameníngea',
        'intramuscular',
        'intramuscular e intradérmica',
        'intramuscular no Vasto Lateral Esquerdo',
        'intramuscular no braço direito',
        'intramuscular.',
        'intraocular',
        'intraperitoneal',
        'intrarraquidiana',
        'intrasinovial',
        'intratecal',
        'intratraqueal',
        'intratumoral',
        'intravascular',
        'intravavenosa',
        'intravelosa',
        'intravemosa',
        'intravemoso',
        'intravempsa',
        'intravenos',
        'intravenosA',
        'intravenosa',
        'intravenosa (não especificado)',
        'intravenosa em bolus',
        'intravenosa injetável',
        'intravenosa&#39,',
        'intravenosa/endovenosa',
        'intravenoso',
        'intravenoso (não especificado de outra forma)',
        'intravenoso (sem outra especificação)',
        'intravenoso direto (sem diluição)',
        'intravenoso não especificado, E2B R2 Code: 050 - Other',
        'intravenoso por bomba de infusão',
        'intravenoso.',
        'intravenossa',
        'intravenous',
        'intravenous (not otherwise specified) (Int)',
        'intravenous (not otherwise specified) (int)',
        'intravenous use',
        'intravenova',
        'intravenoza',
        'intraveosa',
        'intravesical',
        'intravesona',
        'intravitrea',
        'intravitreal',
        'intreavenoso',
        'intretecal',
        'intrevenosa',
        'introvenosa',
        'intrravenoso',
        'intrvenosa',
        'intrvenoso',
        'it',
        'iv',
        'iv direto',
        'iv infusão',
        'iv/im',
        'ivbc',
        'ivbic',
        'máquina de diálise',
        'músculo vasto lateral da coxa direito',
        'ndovenosa',
        'ntratecal e endovenoso',
        'parenteral',
        'peridural',
        'periferica',
        'periferico',
        'perineural',
        'perioferico',
        'por via endovenosa para pré-infusão',
        'primeira dose em bolus seguida de bomba de infusão',
        'punção lombar',
        'pó liófilo',
        'raquianestesia',
        'raquidiana',
        'retrotulbar',
        's.c.',
        'sc',
        'solução endovenosa',
        'solução injetavel',
        'solução injetável',
        'sub cultâneo',
        'sub cutanea',
        'sub cutaneo',
        'sub cutânea',
        'sub cutâneo',
        'sub-cutânea',
        'subaracnoide',
        'subaracnóide',
        'subaracnóidea',
        'subaracnóideo',
        'subccutânea',
        'subconjuntiva',
        'subctanea',
        'subcutanea',
        'subcutaneas',
        'subcutaneo',
        'subcutaneous',
        'subcutânea',
        'subcutânea ao lado direito da barriga',
        'subcutâneo',
        'subcutâneo / oral',
        'subcutâneo.',
        'subcutânia',
        'subutânea',
        'sucutanea',
        'todos por via endovenosa para pré-infusão',
        'tranplacental',
        'tranplacentária',
        'transcutânea',
        'transdermal (transcutaneous)',
        'transmamária',
        'transplacentária',
        'uso intracerebroventricular',
        'uso intraocular',
        'uso intravenoso',
        'vacinada no braço direito, E2B R2 Code: 065 - Unknown',
        'vacinada no braço esquerdo, E2B R2 Code: 065 - Unknown',
        'vacinado no braço esquerdo, E2B R2 Code: 065 - Unknown',
        'vasto lateral da coxa',
        'venoosa',
        'venosa',
        'venoso',
        'ventro glúteo',
        'ventro-gluteal',
        'via EV',
        'via Injeção',
        'via cateter',
        'via catéter epidural',
        'via endovenosa',
        'via endovenosa em infusão com solução fisiológica 0,9%.',
        'via endovenosa – intracoronariana',
        'via endovensosa',
        'via epidural',
        'via indovenosa',
        'via injetavel',
        'via injetável',
        'via intavenosa',
        'via intramuscular',
        'via intraocular',
        'via intratecal',
        'via intravascular',
        'via intravenosa',
        'via intravenosa (1 mg/kg, a cada 3 semanas x 4 doses',
        'via intravenosa direta',
        'via intravenosa ou endovenoso',
        'via intravenosa por gotejamento',
        'via intravenosa.',
        'via intravenoso',
        'via intravenoso direto',
        'via intravesical',
        'via intrevenosa',
        'via introvenosa',
        'via ntravenosa',
        'via peridual',
        'via subcutaena',
        'via subcutanea',
        'via subcutânea',
        'via subcutâneo',
        'via venosa',
        'viaVia intravenosa',
        'vis intravenosa',
        'vis subcutanea',
        '|V',
        '~INTRATECAL',
        '~Intravenosa',
        'Éndovenosa',
        'ÍNTRAVENOSA',
        'Íntravenosa',
        'Útima infusão em 22-Mai-2024',
        'éndovenoso',
    ],
    'R': [
        'RETAL',
        'Retal',
        'VIA RETAL',
        'Via Retal',
        'Via retal',
        'retal',
        'via retal',
    ],
    'SL': [
        'BUCAL',
        'Bucal',
        'Buccal',
        'OROMUCOSA',
        'SL',
        'SUBLINGUAL',
        'Sublingual',
        'Sublingual use',
        'Via sublingual',
        'bucal',
        'dental',
        'gargarejo',
        'orofaringe',
        'sL',
        'sl',
        'sublingual',
        'sublingually',
        'via bucal',
    ],
    'TD': [
        'Cutaneous',
        'Cutaneous use',
        'Cutânea',
        'Dermatológica',
        'INTRADERMICA',
        'Local couro cabeludo',
        'Percutânea',
        'TOPICA',
        'TOPICO',
        'TRANSDERMICA',
        'TRANSDERMICO',
        'TRANSDÈRMICO',
        'TRANSDÉRMICA',
        'Topical',
        'Transdermal',
        'Transdermico',
        'Transdérmica',
        'Transdérmico',
        'TÓPICA',
        'TÓPICO',
        'Tópica',
        'Tópica, com aplicação diretamente no couro cabeludo.',
        'Tópico',
        'Tópico - aplicou apenas nas espinhas',
        'Tópico dermatológico',
        'Uso Cutâneo',
        'Uso cutâneo',
        'Uso transdérmico',
        'Uso tópico',
        'Uso tópico.',
        'VIA TRANSDÉRMICA',
        'VIA TÓPICA',
        'Via transdérmica',
        'Via transdérmico',
        'Via trasdérmico',
        'Via tópica - Couro cabeludo',
        'aplicou Vick no pescoço',
        'cutânea',
        'dermica',
        'intradérmica',
        'local couro cabeludo',
        'retroauricular',
        'subdérmica',
        'topica',
        'topical',
        'topico',
        'trandermico',
        'trandérmico',
        'transdermica',
        'transdermico',
        'transdérmica',
        'transdérmico',
        'tópica',
        'tópico',
        'tópico (transdérmico)',
        'uso dermatológico',
        'uso tópico',
        'via  tópico',
        'via topica',
        'via transdérmica',
        'via tópica',
    ],
    'V': [
        'Intravaginal',
        'Uso vaginal',
        'VAGINAL',
        'Vaginal',
        'intravaginal',
        'vaginal',
        'via vaginal',
    ],
}

BASE_UNKNOWN_TOKENS = [
    "desconhecido",
    "desconhecida",
    "nao informado",
    "não informado",
    "nao informada",
    "não informada",
    "não sei",
    "nao sei",
    "nao reportado",
    "não reportado",
    "outro",
    "outros",
    "outras",
    "unknown",
]


