name: Run elt_bronze_incremental Daily

on:
  schedule:
    - cron: "0 17 * * *"  # 14h de Brasília (17h UTC)
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbconvert

      - name: Run notebook (generate CSVs)
        run: |
          jupyter nbconvert --to notebook --execute --inplace tests/elt_bronze_incremental.ipynb

      - name: Commit and push data updates
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/01_bronze/medicacoes data/01_bronze/notificacoes data/01_bronze/reacoes || echo "No data changes"
          git commit -m "Daily run $(date -u +'%Y-%m-%d'): ELT Bronze" || echo "No changes to commit"
          git push
